# public kiritan data
train_align: /data1/gs/SVS_system/data/public_dataset/kiritan_data/alignment/train
train_pitch: /data1/gs/SVS_system/data/public_dataset/kiritan_data/pitch_beat_extraction/train
train_wav: /data1/gs/SVS_system/data/public_dataset/kiritan_data/wav_info/train
val_align: /data1/gs/SVS_system/data/public_dataset/kiritan_data/alignment/test
val_pitch: /data1/gs/SVS_system/data/public_dataset/kiritan_data/pitch_beat_extraction/test
val_wav: /data1/gs/SVS_system/data/public_dataset/kiritan_data/wav_info/test

# standard: 4
# sing_quality: conf/sing_quality.csv

model_save_dir: exp/rnn_gs

resume: True
mask_free: False
use_asr_post: False
sampling_rate: 22050
nfft: 2048
feat_dim: 1025

n_mels: 80

frame_length: 0.06
frame_shift: 0.03
model_type: GRU_gs
max_epochs: 200
batchsize: 1
num_workers: 10
hidden_size: 512
embedding_size: 512
num_rnn_layers: 3
num_frames: 500
char_max_len: 100
optimizer: adam
lr: 0.001
phone_size: 68
seed: 777
gpu: 1

normalize: True # for utterence normalize

stats_file: exp/rnn_gs/feats_stats.npz
stats_mel_file: exp/rnn_gs/feats_mel_stats.npz
