train_align: /data1/gs/SVS_system/preprocessing/ch_asr/exp/alignment/clean_set/
train_pitch: /data1/gs/SVS_system/preprocessing/ch_asr/exp/pitch_beat_extraction/clean/
train_wav: /data1/gs/annotation/clean/
val_align: /data1/gs/SVS_system/preprocessing/ch_asr/exp/alignment/clean_set/
val_pitch: /data1/gs/SVS_system/preprocessing/ch_asr/exp/pitch_beat_extraction/clean/
val_wav: /data1/gs/annotation/clean/
model_save_dir: exp/debug/model


sampling_rate: 44100
frame_length: 0.06
frame_shift: 0.03
model_type: GLU_Transformer
max_epochs: 10
gradclip: 5
batchsize: 2
hidden_size: 256
dec_nhead: 4
dec_num_block: 6
num_frames: 500
optimizer: noam
noam_scale: 1.0
gradient_accumulation_steps: 1
noam_warmup_steps: 25000
phone_size: 67
seed: 777
gpu: 0
